### ISSUE TITLE
array_unique throws 'Error: Nesting level too deep - recursive dependency?' exception

### ISSUE THREAD

**Issue by Alddar** [SyliusLabs/AssociationHydrator#1]
array_uniqe doesn't use strict comparison, which should always be used when comparing objects.

line 77: `->setParameter('subjects', array_unique($subjects, \SORT_REGULAR))`

**Comment by dnna** [comment]
I also encountered this problem. I have created a PR that uses the doctrine ids instead of array_unique to isolate the unique entities.

**Comment by pamil** [comment]
I'll try to get a look at it today, it makes me think of introducing some tests in this library which was a quick hack to boost performance at first :)

**Comment by dnna** [comment]
@pamil could you tag a release with the fix?
