### ISSUE TITLE
Release new version on Packagist?

### ISSUE THREAD

**Issue by jhogervorst** [SyliusLabs/AssociationHydrator#11]
I see Symfony 6 compatibility is already present on `master`, but those changes are not yet released. The latest version on Packagist is v1.1.4.

It would be nice if you could release a new version that includes these changes 🙌

**Comment by NoResponseMate** [comment]
Hi @jhogervorst 👋 

Sorry for the late reply.
Symfony 6 compatibility was released a while ago in version 1.2.0.

Cheers 🍻
